manifest:
  defaults:
    revision: v0.3.0
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: view
      url-base: https://github.com/DynamicWhiteHat
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: nice-view-gem-rotated
      remote: view
      revision: main
  self:
    path: config